@startuml

class CrosstabExt {
  config: Object
  measure: String
  globalData: Object[ ]
  colDimensions: String[ ]
  rowDimensions: String[ ]
  measureOnRow: Boolean

  renderTable()
  reorderRow(String, Number)
  reorderColumn(String, Number)
}

interface MultiChartExt {
  init(): Void
  draw(): Void
  dispose(): Void
}

class TableManager {
  constructTable()
  createRowCells()
  supplyGridData()
  createColumnCells()
}

class Field {
  primaryDimension: String
  dimensionArray: Dimension [ ]
  getSplitData(DataStore): DataStore [ ]
  swapDimensions(Dimension, Number)
}

CrosstabExt .u.> MultiChartExt

@enduml
